# Generated by Django 5.1.4 on 2025-01-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_coreapp', '0003_alter_profile_profileimg_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
